apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ywonchae1/teamsoccer-client
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: client-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer
  ports:
  - port: 80
  # targetPort: 3000
  selector:
    app: client