version: "3.8"

services:
  frontend:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - '80:80'
    env_file: .env